### ISSUE TITLE
Readme? Database?

### ISSUE THREAD

**Issue by enkodellc** [patrickgod/BlazingShop#1]
Hi Patrick I started watching your youtube series to try and implement your blazorshop. I was expecting your seeding to work out the box. I am not great at EF, tried **update-database** but no luck. I guess I will try and watch some more of your videos.

**Comment by patrickgod** [comment]
Hi Keith,
Thanks for reaching out!
I just added a Readme file that hopefully answers all your questions.
Take care,
Patrick

**Comment by enkodellc** [comment]
@patrickgod  great thanks, I forgot to change my path!
